### PR TITLE
Some small changes which also made the image smaller!

### PR DESCRIPTION
**Pull request by robbyoconnor**
I have small changes and also managed to get the size down -- even with adding
dumb-init to the image!

I am using this as a base for something and wanted to contribute back. I also merged the backup scripts into one script as opposed to two. 

Before: **10.4 MB**
After: **9.83MB**

### CODE REVIEW

**Comment by robbyoconnor** [comment]
$ docker images|grep cron                                                   
cron                                         latest              881a6a41a2ad        16 minutes ago      9.83MB
openmrs/cron-backup                          latest              d852cecdd775        9 months ago        10.4MB

**Comment by robbyoconnor** [comment]
Compressed size is 4 MB vs 4.9MB from the previous -- I also simplified things and added a dockerignore file.

**Comment by robbyoconnor** [comment]
Ready for review

**Review by cintiadr — APPROVED** [review]
LGTM

**Comment by robbyoconnor** [comment]
Given your approval, I am going to merge this.

**Comment by robbyoconnor** [comment]
Snuck in a commit amend quickly.

**Pull request merged**
